### ISSUE TITLE
Refactor model_summaries() to use bbi/Go parallelism

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#395]
When `model_summaries()` was implemented (#53 and #117) we decided just to repeatedly call `bbi nonmem summary` under the hood for each model. This was relatively fast and much easier to implement.

However, `bbi` has the capability to [accept multiple models](https://github.com/metrumresearchgroup/bbi/blob/develop/cmd/summary.go#L74-L160) to the `bbi nonmem summary` call, which would then use Go routines to run the summaries in parallel. This has been in `bbi` [since June 2020](https://github.com/metrumresearchgroup/bbi/pull/171).

The speed of `model_summaries()` is not an issue when only summarizing a couple models, but it has been noted several times that it is prohibitive for large numbers of models (e.g. a bootstrap). This was a big part of the motivation for the batch parameter estimates function (#147). However, there are times when the user might want other information (for example heuristics) from a large number of models.

**Comment by seth127** [comment]
Consider whether this will require constraining the `bbi` version and, if so, can we have a switch where `model_summaries()` works with any version of `bbi` but automatically works in parallel if the version of `bbi` is new enough.

This code may be ugly, but it seems like obviously the right move.

**Comment by rymarinelli** [comment]
Stories:
```
INT-PAR-001:
  name: Use concurrency when summarizing models 
  description:  As a user, I want to be able to run models in parallel in bbi. 
   This should be done to address computational issues when bootstrapping.
  ProductRisk: Low
  Requirements:
     -INT-PAR-002
    -INT-PAR-003
    -INT-PAR-004
```
Requirements:  
```  
 INT-PAR-002:
  description: the JSON results of models should return in the same order of the input
  tests: 
 INT-PAR-003:
  description: confirm that race conditions will not alter the order of the returns 
  tests: 
 INT-PAR-004:
  description: ensure that model errors are logged 
  tests: 
```
