### ISSUE TITLE
format_tags_diff()

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#404]
Makes a nicely formatted column for HTML `log_df` tables that shows the tags added and removed

# Discussion Points

* this is fairly specific to HTML formatting. We should test with pdf and other rendering stuff and see if we need to change anything, or maybe make an argument like `format = c("html", "pdf")` or something.
* We should also test how this interacts with `knitr::kable()`

# Proposed Code

```r
format_tags_diff <- function(.log_df, .keep = FALSE) {
  if (
    !any(str_detect(names(.log_df), "tags_added")) ||
    !any(str_detect(names(.log_df), "tags_removed"))
  ) {
    stop("Must have both `tags_added` and `tags_removed` columns to call `format_tags_diff()`. Use `add_tags_diff()` to create them")
  }
  .log_df <- bbr::suppressSpecificWarning(
    collapse_to_string(.log_df, tags_added, tags_removed),
    .regexpr = "collapse_to_string\\(\\) only works on list columns"
  ) %>%
    mutate(
      tags_diff = paste0(tags_added, "; ~~", tags_removed, "~~") %>% 
        str_replace("; ~~~~","") %>% 
        str_replace("^; ", "")
    )
  if (isFALSE(.keep)) {
    .log_df <- select(.log_df, -tags_added, -tags_removed)
  }
  return(.log_df)
}
```

**Comment by barrettk** [comment]
@seth im not sure this function is right unless im missing something (I know its WIP). Im finding that `tags_added` and `tags_removed` are not necessarily names of `tags_diff(log_df)`, but rather one level down:
```r
> tags_diff(log_df)
$`1`
$`1`$tags_added
[1] "acop tag"  "other tag"

$`1`$tags_removed
[1] ""


$`2`
$`2`$tags_added
[1] "new tag 1" "new tag 2"

$`2`$tags_removed
[1] "acop tag"  "other tag"


$`3`
$`3`$tags_added
[1] "the newest"

$`3`$tags_removed
[1] "other tag" "new tag 2"
```

Im going to write the stories/requirements assuming my assumption is correct. Wanted to give it a run before writing them to have a better understanding of functionality, but I can definitely put something together for whats here right now

**Comment by barrettk** [comment]
Stories:
```
MGMT-S013 (this already exists):
  name: format tags difference
  description: As a user, I want to be able to see the difference in the tags element
    of different models. Be able to either compare two models directly, or compare
    all models in a `bbi_run_log_df` to their "parent models" (i.e. the models in
    that same tibble that match their `based_on`).
  ProductRisk: Medium
  Requirements:
     - (requirements of previous tests)
     - MGMT-R011
     - MGMT-R012
```

_New_ Requirements:
```
MGMT-R011:
  description: format_tags_diff() should turn the output of `tags_diff(log_df)` into a nicely formatted html or PDF table
  tests: 
MGMT-R012:
  description: format_tags_diff() should create a `tags_diff` column for each model and optionally allow `tags_added` and `tags_removed` to remain in the output
  tests: 
```

**Comment by seth127** [comment]
This is sort of right but the issue that you're looking at the output of `tags_diff()` and this will actually be from `add_tags_diff()`. See the "Value" section of [these docs](https://metrumresearchgroup.github.io/bbr/reference/tags_diff.html) for the distinction.

As discussed offline, this might be better as a `.format` argument to `add_tags_diff()`. Proposed behavior:

* Defaults to `NULL`, causing the returned tibble to have `tags_added` and `tags_removed` (current behavior)
* Can pass `add_tags_diff(..., .format = "html")` which would cause the returned tibble to have only `tags_diff` column added to it, which would be formatted so that it renders as HTML (when someone passes this to `knitr::kable()` or whatever)
* Theoretically `.format` could take other things like `"pdf"` if we someday want to implement that.

**Comment by barrettk** [comment]
Im a bit unclear as to what the regex replacements are supposed to be doing. I get the following: 
![image](https://user-images.githubusercontent.com/18685116/173434534-aa939613-71a9-4f20-90f1-2ed7ca05311f.png)

Should the removed tags be italicized?

**Comment by barrettk** [comment]
New Requirement:
```yaml
TDF-R005:
  description: add_tags_diff() can optionally append a new column with html formatting
  tests:
  - BBR-TDF-005
  - BBR-TDF-006
```

Added to story:
```yaml
MGMT-S013:
  name: Tags diff
  description: As a user, I want to be able to see the difference in the tags element
    of different models. Be able to either compare two models directly, or compare
    all models in a `bbi_run_log_df` to their "parent models" (i.e. the models in
    that same tibble that match their `based_on`).
  ProductRisk: Low
  requirements:
  - TDF-R001 (previous)
  - TDF-R002 (previous)
  - TDF-R003 (previous)
  - TDF-R004 (previous)
  - TDF-R005 (new)
```
