### ISSUE TITLE
Pull ETA p-value estimates into parameter table

### ISSUE THREAD

**Issue by callistosp** [metrumresearchgroup/bbr#458]
# Problem
One of the heuristics reported by bbr is `eta_pval_significant`. Currently there is no easy way to identify which ETAs are flagged by this heuristic without manually opening the LST file.

# Proposed Solution
We are already pulling in the p-value to generate the heuristic flag. It would be helpful to have a pipeable function which could append the p-value to the param_estimates() output.

Here's my hacky implementation based on the current data structure of the model_summary object:
```
> (.s <- mod %>% model_summary())
> .s %>% param_estimates() %>% 
+   filter(str_detect(parameter_names, "OMEGA") & diag == TRUE) %>% 
+   bind_cols(data.frame(pval=.s$shrinkage_details[length(.s$shrinkage_details)][[1]][[1]]$pval)) %>% 
+   mutate(ETASIG = pval<0.05)
```
Notice that `length(.s$shrinkage_details)` is used to grab estimates from the final estimation method if multiple are used. I'm also generating a new column `ETASIG` which just flags if the p-value is less that 0.05 (not necessary, but may be nice to include to quickly see which OMEGA is causing the flag to be raised)

**Comment by seth127** [comment]
Would you see this this a function that would take the df that's output from `param_estimates()` so that you could pipe it like you do above? In that case, it would basically return the same df, but with the new column appended. I like that idea.

**Comment by callistosp** [comment]
@seth127 yes, that's exactly what I was thinking. Either a pipeable function, or you could add an argument to `param_estimates` that would append it when called, e.g. `param_estimates(..., .pval=TRUE)`

**Comment by seth127** [comment]
Thanks, that makes sense.

> you could add an argument to param_estimates

I kinda like this approach actually. We'll think on that.

**Comment by barrettk** [comment]
I like the idea of making this a new argument as well (likely two, one logical (T/F), and one denoting the p-value (defaulting to 0.05). Given its relationship to `param_estimates()`, I dont think it makes sense to make this into a new function. Will append the stories/requirements with that assumption for now:

```yaml
SUM-S002:
  name: Read NONMEM parameter table
  description: As a user, I want to be able to load the parameter estimates from the
    final estimation method of a NONMEM model into a tibble in R.
  ProductRisk: Low
  requirements:
  - PEST-R001 (previous requirement)
  - PEST-R013 (new requirement - should be added to story since it will be another argument)
  - WRKF-R001 (previous requirement)
  - WRKF-R002 (previous requirement)
```   
     
_New_ Requirements:
```yaml
PEST-R013 :
  description: param_estimates() can optionally append the p-value to the output, and calculate whether it is below a specified value
  tests: 
```

(will likely need to add multiple tests for this requirement)

It might make sense to address [this issue](https://github.com/metrumresearchgroup/bbr/issues/494) before assigning new test ids
