### ISSUE TITLE
Starred models

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/bbr#474]
# Summary

As a user, I want to be able to star certain models to indicate special interest level

@riggsmm

**Comment by seth127** [comment]
Story:

```yaml
MGMT-S016:
  name: Starred models
  description: As a user, I want to be able to star certain models to indicate special interest level.
  ProductRisk: Medium
  requirements:
  - MGMT-R015
  - MGMT-R016
  - MGMT-R017
```

Requirements:

```yaml
MGMT-R015:
  description: Model object and YAML should have a boolean star attribute
  tests:
MGMT-R016:
  description: Star attribute should be parsed into `run_log()` tibble
  tests:
MGMT-R017:
  description: `add_star()` and `remove_star()` helpers for modifying model object
  tests:
```
