### ISSUE TITLE
wait_from_nonmem() helper

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#479]
# Summary

There are situations where we want to monitor whether a NONMEM run has completed. Note that we don't care (in these situations) whether it finished _successfully_ in any sense, just whether it is still running. This is not trivial because these models are often submitted to run on worker nodes in a grid, so we can't just check for the process ID.

# Notes

Initial idea is to check the `.lst` file for "Stop Time". This seems to work for most cases, but there are some things to consider.

* Need to check whether this works if you kill a model
  * submitted locally and killed with process ID `kill -9 <pid>`
  * submitted to SGE and killed with `qdel`
* Need to check if it works in all NONMEM failures
  * if it dies early (i.e. can't find the data set) does it still print "Stop Time"?

# Requirements

* Should be able to take multiple models
* Should be a helper `check_nonmem_finished()` (also exported) to check a single model one-off
* Should take an arg for interval to check
* Should take an arg for total time limit (so this doesn't hang indefinitely)

**Comment by barrettk** [comment]
Stories:
```
MGMT-S019:
  name: wait_for_nonmem
  description: As a user, I want to be able to freeze my R console while a model is executing on the grid or otherwise
  ProductRisk: Medium
  Requirements:
     - MGMT-R010
```

Requirements:
```
MGMT-R010:
  description: wait_for_nonmem() will freeze the console until a stop time is found or the allotted time is reached
  tests: 
     - BBR-UTL-012
     - BBR-UTL-013

```
