### ISSUE TITLE
delete model helper

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#482]
It might be nice to have a `delete_model()` helper, in part for our test suite, but also for users. This function would take a model object and delete (on disk)

* the bbr-created YAML file
* the control stream
* the output directory

Probably also remove the model object from memory? Kind of a weird idea, but probably right.

**Comment by seth127** [comment]
Related, an idea from @barrettk of wanting to loop over and delete all models with a certain tag. This was relevant to testing #473 originally, but could have other use cases.

> ... It could be generalized further, but it also adds another purpose to add tags if we wanted to add another tags argument to the function:

```r
cleanup_mods <- function(mods){
  # Only remove mods with correct tag
  mod_paths <- lapply(mods, function(mod.x){mod.x$absolute_model_path})# %>% unlist()
  mod_threads <- lapply(mods, function(mod.x){mod.x$bbi_args$threads})
  mod_tags <- lapply(mods, function(mod.x){mod.x$tags})

  mods_remove <- map2(mod_tags, mod_threads, function(tag.x, thread.y){
    grepl(paste("test", thread.y, "threads"), tag.x)
  }) %>% unlist()

  mod_paths <- mod_paths[mods_remove] %>% unlist()

  for (m in mod_paths) {
    if (fs::file_exists(yaml_ext(m))) fs::file_delete(yaml_ext(m))
    if (fs::file_exists(ctl_ext(m))) fs::file_delete(ctl_ext(m))
    if (fs::dir_exists(m)) fs::dir_delete(m)
  }
  message("Removed models with the following tags:\n", paste("-",unlist(mod_tags), collapse = "\n"))
}
```

> This function works because I modified the mods call to add those tags:

```r
  .mods <- map(threads, ~ copy_model_from(.mod, paste0(get_model_id(.mod), "_", .x, "_threads")) %>%
                 add_bbi_args(.bbi_args = c(threads = .x,
                                            .bbi_args,
                                            parallel = TRUE,
                                            overwrite = TRUE)) %>%
                 add_tags(paste("test",.x,"threads")))
```

**Comment by kylebaron** [comment]
@seth127 This could work for models in a `git` repository but would create problems with subversion. I know we're heading that direction but caution as long as subversion is in the mix.

**Comment by seth127** [comment]
hmmm, I'm not sure what you mean @kylebaron, though admittedly I don't know much about SVN. We're just talking about deleting the files on disk, not touching anything about how they're version controlled. Is there some subtlety I'm missing though?

**Comment by kylebaron** [comment]
If you delete the file before adding it to the repository, then it's fine. But if you add a file (or directory) to the repository and then delete it `file_delete()` it will come back the next time you run `svn update`.  It can cause a lot of headaches if you run `rm 1001.ctl` rather than `svn rm 1001.ctl`. You could make it honor system ... "don't run this on models that have already been added"; but it seems like chances are high it won't work as expected.

**Comment by seth127** [comment]
ok, this makes sense @kylebaron. Similar issue in git, though we could theoretically build in a `git rm` under the hood. That's probably dangerous though, and I don't know if there's even an analogous thing in SVN.

Honestly, this probably is most useful for testing and demos. In most cases it seems like people keep around all of the models they run, even if they didn't end up being "good" models. At least once they've checked them in.

**Comment by barrettk** [comment]
FYI @seth127 I modified that function (for use in the test_threads PR) to have a `.tags` argument:

```
#' Remove model files associated with the specified tags
#'
#' @param .mods a bbi model object or list of model objects.
#' @param .tags a character vector identifying the tags of the models you want to delete.
#'              If set to NULL, delete all associated model files.
#'
#' @importFrom checkmate check_character
#'
#' @export
cleanup_mods <- function(.mods, .tags = NULL){
  if(!is.null(.tags)) check_character(.tags)
  # Only remove mods with correct tag
  mod_paths <- lapply(.mods, function(mod.x){mod.x$absolute_model_path})
  mod_threads <- lapply(.mods, function(mod.x){mod.x$bbi_args$threads})
  mod_tags <- lapply(.mods, function(mod.x){mod.x$tags})

  mods_remove <- if(is.null(.tags)){
    rep(TRUE, length(mod_tags))
  }else{
    map2(mod_tags, .tags, function(tag.x, .tag){
      grepl(.tag, tag.x)
    }) %>% unlist()
  }

  if(!all(mods_remove)){
    stop("None of specified tags were found")
  }

  mod_paths <- mod_paths[mods_remove] %>% unlist()

  for (m in mod_paths) {
    if (fs::file_exists(yaml_ext(m))) fs::file_delete(yaml_ext(m))
    if (fs::file_exists(ctl_ext(m))) fs::file_delete(ctl_ext(m))
    if (fs::dir_exists(m)) fs::dir_delete(m)
  }
  message("Removed models with the following tags:\n", paste("-",unlist(mod_tags[mods_remove]), collapse = "\n"))
}
```

**Comment by seth127** [comment]
Will be closed by #473

**Comment by barrettk** [comment]
Mentioned these stories/requirements [here](https://github.com/metrumresearchgroup/bbr/issues/488#issuecomment-1145358906), but reposting the delete_model specifics again here

Stories:
```
MGMT-S016:
  name: Cleanup model files
  description: As a user, I want to be able to easily delete all model files associated
       the identified model objects.
  ProductRisk: Medium
  Requirements:
    - MGMT-R001
    - MGMT-R002
    - MGMT-R003
```

Requirements:
```
MGMT-R001:
  description: delete_models() should work for test_threads() by default
  tests: 
     - BBR-CLM-001
MGMT-R002:
  description: delete_models() should only delete models with the specified .tags by default
  tests:
     - BBR-CLM-002
     - BBR-CLM-003
MGMT-R003:
  description: delete_models() should delete all specified models if .tags = NULL
  tests:
     - BBR-CLM-004
```
