### ISSUE TITLE
test_threads() patches

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#488]
#473 created a new function `test_threads()` (among others). It has been merged to `develop` but before release we are doing some user testing. This issue encapsulates changes we plan to make based on feedback from that user testing. Detailed descriptions in comments.

- [x] returns empty for non-parallel model
- [x] suppress incomplete final line warning
- [x] if any of the `model_summaries()` calls fail, `check_run_times()` returns `NA`
- [x] rename `model_run` column to `run` for consistency ([here](https://github.com/metrumresearchgroup/bbr/blob/develop/R/test-threads.R#L179))
- [x] look into pulling threads from somewhere _other than_ `$bbi_args$threads` (potentially `bbi_config.json`)

**Comment by seth127** [comment]
# returns empty for non-parallel model

If `$bbi_args$threads` is empty (i.e. the model was _not_ run in parallel) [here](https://github.com/metrumresearchgroup/bbr/blob/develop/R/test-threads.R#L169) or [here](https://github.com/metrumresearchgroup/bbr/blob/develop/R/test-threads.R#L173) it will cause the tibble returned on [from the map](https://github.com/metrumresearchgroup/bbr/blob/develop/R/test-threads.R#L178) to have 0 rows, effectively skipping that model.

Instead, if `$bbi_args$threads` is empty, set `threads <- 1` to indicate this model was run on a single thread.

**Comment by seth127** [comment]
# incomplete final line

Add a `suppressSpecificWarning(.regexp = "incomplete final line") to [this `readLines()` call](https://github.com/metrumresearchgroup/bbr/blob/develop/R/test-threads.R#L76)

**Comment by seth127** [comment]
# `check_run_times()` returns `NA`

`check_run_times()` should always return a tibble with the columns: `run, threads, all_of(.return_times)` 

Currently it returns `NA` if any of the `model_summary()` calls fail, and it returns `TRUE` if `wait_for_nonmem()` doesn't finish.

## Proposed Fix

Move the `tryCatch()` on line 156 to instead wrap the [interior of the map function](https://github.com/metrumresearchgroup/bbr/blob/develop/R/test-threads.R#L160-L184). If an error is caught, return an one-row tibble with columns: `run, threads, all_of(.return_times)`, with `run` filled in and everything else `NA` 

`wait_for_nonmem()` should be outside of the `tryCatch()`. It will warn if some models haven't finished, which is fine. It will then proceed to the `map` call and the models that _have_ finished will get parsed successfully.

**Comment by barrettk** [comment]
> # returns empty for non-parallel model
> If `$bbi_args$threads` is empty (i.e. the model was _not_ run in parallel) [here](https://github.com/metrumresearchgroup/bbr/blob/develop/R/test-threads.R#L169) or [here](https://github.com/metrumresearchgroup/bbr/blob/develop/R/test-threads.R#L173) it will cause the tibble returned on [from the map](https://github.com/metrumresearchgroup/bbr/blob/develop/R/test-threads.R#L178) to have 0 rows, effectively skipping that model.
> 
> Instead, if `$bbi_args$threads` is empty, set `threads <- 1` to indicate this model was run on a single thread.

I made this 1 row, because you mentioned wanting the `run` to still show in the dataframe

**Comment by seth127** [comment]
> Something else thats interesting, is why theres a discrepancy between run 1 and run 1_4_threads, given that threads is 4 in both cases (same thing for run 100 and run 100_1_threads). Would imagine that the estimation time doesn't include the time required to spin up a node (if it was done on sge), but not sure.

I think this is because we cap `MAXEVAL` for the `_threads` ones, so they will be faster. They can really only be compared to each other.

**Comment by barrettk** [comment]
Stories:
```
MGMT-S016:
  name: Cleanup model files
  description: As a user, I want to be able to easily delete all model files associated
    the identified model objects.
  ProductRisk: Medium
  Requirements:
  - MGMT-R001
  - MGMT-R002
  - MGMT-R003
 
MGMT-S017:
  name: test threads
  description: As a user, I want to be able to test variations of parallelization on a given model by specifying the number of 
       threads and max number of iterations (MAXEVAL or NITER)
  ProductRisk: Medium
  Requirements:
     - MGMT-R004
     - MGMT-R005
```

Requirements:
```
MGMT-R001:
  description: delete_models() should work for test_threads() by default
  tests: 
     - BBR-CLM-001
MGMT-R002:
  description: delete_models() should only delete models with the specified .tags by default
  tests:
     - BBR-CLM-002
     - BBR-CLM-003
MGMT-R003:
  description: delete_models() should delete all specified models if .tags = NULL
  tests:
     - BBR-CLM-004

MGMT-R004:
  description: test_threads(.dry_run=T) creates a duplicate model for each specified thread
  tests: 
     - BBR-TSTT-001
     - BBR-TSTT-003
MGMT-R005:
  description: test_threads(.dry_run=T) correctly adjusts MAXEVAL/NITER and handles incorrect specifications in the control 
     stream
  tests: 
     - BBR-TSTT-002
     - BBR-TSTT-004
```

Need to still add requirements for `check_run_times()`
