### ISSUE TITLE
Consider changing all _log() functions to default to .recurse = FALSE

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#492]
Functions `run_log()`, `summary_log()`, and `config_log()` all default to searching for models recursively in sub directories. However, user feedback tells us:

* Typically users organize their models by directory and intend to create separate run logs for each group of models (i.e. each directory)
* This causes problems when something like a bootstrap is in a subdirectory (common practice) because then the log attempts to read in all of the bootstrap models as well, making the log huge and unreadable

We should consider changing the this default so that users would have to specify `.recurse = TRUE` to search sub directories.

**Comment by barrettk** [comment]
Stories:
```
LOG-S002 (this already exists):
  name: Working directory and paths in run log tibble are correct
  description: As a user, I want to be able to use the paths included in the run_log()
    output to unambiguously find model input and output files. A user should be able
    to do this, even when the models were run on a different machine or in a different
    directory than the one in which they are currently being read (by run_log()).
  ProductRisk: Low
  Requirements:
     - (requirements of previous tests)
     - LOG-R011
     - LOG-R012
     - LOG-R013
```

_New_ Requirements:
```
LOG-R011:
  description: run_log() can optionally look in subdirectories via the `.recurse` argument
  tests: 
LOG-R012:
  description: summary_log() can optionally look in subdirectories via the `.recurse` argument
  tests: 
LOG-R013:
  description: config_log() can optionally look in subdirectories via the `.recurse` argument
  tests: 
```
