### ISSUE TITLE
Requirement is missing information

### ISSUE THREAD

**Issue by barrettk** [metrumresearchgroup/bbr#494]
I believe the below requirement is missing word(s) at the end of the description

see `inst/validation/bbr-requirements.yaml` line 625:
```yml
PEST-R003:
  description: param_estimates correctly errors on
  tests:
  - BBR-PEST-003
```
