### ISSUE TITLE
`bbi_init`: parse `nmfe_options` separately from other `.bbi_args`

### ISSUE THREAD

**Issue by barrettk** [metrumresearchgroup/bbr#714]
The following `.bbi_args` would be listed under `nmfe_options` within a given `bbi.yaml`. `maxlim` is automatically set to `2`:
 - `prdefault`
 - `tprdefault`
 - `maxlim`

Example `bbi.yaml`
```yaml
clean_lvl: 1
local:
  create_child_dirs: yes
mpi_exec_path: /usr/bin/mpiexec
nmfe_options:
  prdefault: true # not a default - currently must be manually added
  tprdefault: true # not a default - currently must be manually added
  maxlim: 2.0
...
parallel: no
threads: 2
```

However, when `.bbi_args` are added via the comment below, they are all treated the same:
```r
bbi_init(.bbi_args = list(prdefault = TRUE, tprdefault = TRUE, maxlim = 2))
```
...which would _**not**_ place those arguments under `nmfe_options`. In that case  `bbi` would both ignore those arguments. Only nmfe options specifically listed under `nmfe_options` would have the desired effect. 

If that's the case, the only way to really pass these options would be via `.bbi_args` in  `submit_model`, or as part of the model object:
```r
mod <-  add_bbi_args(mod, list(prdefault = TRUE))
```

```r
submit_model(mod, .bbi_args = list(prdefault = TRUE))
```

Additional context:
 - https://github.com/metrumresearchgroup/bbr/pull/705#discussion_r1697173698
 - https://github.com/metrumresearchgroup/bbr/pull/705#discussion_r1697197169
